import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('测试设计页面拆分为固定流程面板且不展示多 Agent DAG', () => {
  const page = read('../src/test-design/TestDesignPage.tsx')
  for (const panel of ['TestDesignCreatePanel', 'TestDesignRunPanel', 'TestCasePanel', 'CoverageAuditPanel', 'TestDesignPublicationPanel', 'TestCaseLibraryPanel', 'TestSuiteLibraryPanel']) assert.match(page, new RegExp(panel, 'u'))
  for (const entry of ['设计任务', '测试用例库', '测试套件', '发布记录']) assert.match(page, new RegExp(entry, 'u'))
  assert.doesNotMatch(page, /TestDataRequirementPanel|CaseChangeProposalPanel/u)
  assert.doesNotMatch(page, /ExecutionHandoffPanel/u)
  assert.doesNotMatch(page, /TestAnalysisAgent|FunctionalTestDesignAgent|NonFunctionalTestDesignAgent|TestCaseSynthesisAgent|scope_gate|tree_merge/u)
  assert.match(read('../src/RequirementAnalysisPageV2.tsx'), /\.\/test-design\/TestDesignPage/u)
})

test('需求分析页面只在当前选择的成功 Requirement Release Run 上开放测试设计，新建对话仍须先分析', () => {
  const source = read('../src/RequirementAnalysisPageV2.tsx')
  const api = read('../src/test-design/api.ts')
  const analysisApi = read('../src/requirement-analysis-api.ts')
  const routes = read('../server/http/test-design-routes.ts')
  const service = read('../server/application/test-design-service.ts')
  const styles = read('../src/requirement-analysis-v2.css')
  assert.match(source, /const releaseBindings = projectVersion\?\.requirementReleaseBindings/u)
  assert.match(source, /const selectedReleaseBinding = selectedRun \? releaseBindings\.find/u)
  assert.match(source, /const testDesignReady = Boolean\(selectedRun && selectedReleaseBinding/u)
  assert.match(source, /const releasePublished = release\?\.status === 'published'/u)
  assert.match(source, /void refreshProjectVersions\(\)\.catch/u)
  assert.match(source, /const testDesignRunComplete = linkedTestDesignRun\?\.status === 'succeeded'/u)
  assert.match(source, /已生成 \$\{activeTestDesignCases\.length\} 条候选用例/u)
  assert.match(source, /\$\{activeTestDesignCases\.length\} 条候选用例待审核与发布/u)
  assert.doesNotMatch(source, /测试设计运行已创建，请查看实时进度/u)
  assert.match(source, /const selectedRun = runs\.find\(run => run\.id === selectedRunId\)/u)
  assert.match(source, /<option value="">新建对话<\/option>/u)
  assert.match(source, /新建对话（未创建 Run）/u)
  assert.match(source, /本次需求分析尚未发布/u)
  assert.match(source, /请先完成需求分析/u)
  assert.match(source, /loadRun as loadTestDesignRun/u)
  assert.match(source, /<TestDesignConversationEntry linkage=\{linkedTestDesign\}/u)
  assert.doesNotMatch(source, /测试点设计|RequirementCoverage/u)
  assert.match(source, /测试设计已停止/u)
  for (const contract of ['loadLibraryVersions', 'loadLibraryHandoffs', 'sourceRunId === linkedTestDesign.runId', 'testCaseLibraryVersionId === libraryVersion.id', '测试用例候选', '尚未发布正式用例库', '正式测试用例库', '非正式']) assert.match(source, new RegExp(contract, 'u'))
  assert.doesNotMatch(source, /machineReadableArtifactNames|releaseArtifacts\.map\(artifact/u)
  assert.match(source, /PostgreSQL 中的不可变结构化 content 是唯一正式机器事实/u)
  assert.match(source, /requirement-analysis\.md/u)
  assert.match(source, /查看需求分析报告/u)
  assert.match(source, /release\.content\.requirements\.length/u)
  assert.doesNotMatch(source, /const formalContentHashes = new Set/u)
  assert.match(source, /const candidateArtifacts = release \? \[\] : result\?\.artifacts \?\? \[\]/u)
  assert.match(source, /candidateArtifacts\.length>0/u)
  assert.match(source, /candidateArtifacts\.map\(item/u)
  assert.doesNotMatch(source, /可读需求基线/u)
  assert.doesNotMatch(source, /release\.artifacts\.filter\(item=>machineNames/u)
  assert.doesNotMatch(source, /isRequirementSourceSnapshotArtifact|需求原文快照/u)
  assert.match(api, /sourceRunId=\$\{encodeURIComponent\(sourceRunId\)\}/u)
  assert.match(api, /libraryVersionId=\$\{encodeURIComponent\(libraryVersionId\)\}/u)
  assert.match(routes, /url\.searchParams\.get\('sourceRunId'\)/u)
  assert.match(routes, /url\.searchParams\.get\('libraryVersionId'\)/u)
  assert.match(service, /!sourceRunId \|\| item\.sourceRunId === sourceRunId/u)
  for (const previewContract of ['ArtifactPreview', 'loadRequirementReleaseArtifact', '<Eye />预览', "value.mediaType === 'text/markdown'", 'JSON.stringify(JSON.parse(value.content), null, 2)']) assert.match(source, new RegExp(previewContract.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&'), 'u'))
  assert.doesNotMatch(source, /requirementReleaseArtifactUrl|download=\{artifact\.fileName/u)
  assert.match(analysisApi, /export async function loadRequirementReleaseArtifact/u)
  assert.match(styles, /\.rav2-artifact-list article>button/u)
  assert.match(styles, /\.rav2-artifact-preview \.rav2-source-body>pre/u)
})

test('创建面板展示绑定需求发布包，并只读展示 ProjectVersion 自动历史基线', () => {
  const source = read('../src/test-design/TestDesignCreatePanel.tsx')
  assert.match(source, /Requirement Release/u)
  assert.match(source, /requirementReleases/u)
  assert.match(source, /requirementReleaseId/u)
  assert.match(source, /releaseId/u)
  assert.match(source, /纳入范围/u)
  assert.match(source, /排除范围/u)
  assert.match(source, /测试维度/u)
  assert.match(source, /执行入口/u)
  assert.match(source, /historicalBaseline\.status === 'source_library_available'/u)
  assert.match(source, /继承用例库：正式用例库 V/u)
  assert.match(source, /该基线由版本继承关系自动确定/u)
  assert.match(source, /来源版本暂无正式测试用例库，本次将按无历史基线生成/u)
  assert.match(source, /当前版本未继承来源版本，本次测试设计不加载历史用例/u)
  assert.doesNotMatch(source, /历史用例策略|historyMode|historyVersionId|指定来源用例库版本|指定来源测试套件|不使用历史用例/u)
  assert.doesNotMatch(read('../src/test-design/types.ts'), /historicalLibrarySelection/u)
  assert.doesNotMatch(source, /默认选择当前项目版本其他 Run/u)
  assert.doesNotMatch(source, /basisMode|review_baseline|sourceTechnicalSolutionRunId/u)
})

test('历史匹配由 Service 管理且审核页不暴露 Proposal', () => {
  const page = read('../src/test-design/TestDesignPage.tsx')
  const service = read('../server/application/test-design-service.ts')
  assert.doesNotMatch(page, /CaseChangeProposalPanel|用例库变更/u)
  assert.match(service, /matchHistoricalCandidate/u)
  assert.match(service, /buildEffectiveCaseSet/u)
  assert.match(service, /materializeCaseChangeProposals/u)
  assert.match(service, /reconcileAutomaticProposalDecisions/u)
  assert.match(service, /TEST_DESIGN_SERVICE_ACTOR_ID/u)
})

test('运行面板展示冻结配置与折叠技术诊断，Agent 轨迹统一进入主界面协作', () => {
  const source = read('../src/test-design/TestDesignRunPanel.tsx')
  const planningPage = read('../src/RequirementAnalysisPageV2.tsx')
  assert.match(source, /Requirement Release/u)
  assert.match(source, /verificationRunId/u)
  assert.match(source, /requirementReleaseContentSha256/u)
  assert.match(source, /Workspace Snapshot/u)
  assert.match(source, /Agent 配置快照/u)
  assert.match(source, /技术诊断/u)
  assert.doesNotMatch(source, /Pi Agent 实时轨迹/u)
  assert.match(planningPage, /TestDesignNodeConversationEntry/u)
  assert.match(planningPage, /totalEventCount/u)
  assert.match(planningPage, /testDesignExecutions/u)
  assert.match(source, /Coverage 检查/u)
  for (const baselineState of ['当前 ProjectVersion 未启用版本继承', '来源版本暂无正式 TestCase Library', '本次 Run 按空 Historical Baseline 执行', '正式用例库：', '历史用例：']) assert.match(source, new RegExp(baselineState, 'u'))
  assert.match(source, /AI Coverage 复核/u)
  assert.match(source, /当前 TestCase 最新 Revision/u)
  assert.match(source, /开始 Coverage AI 复核/u)
  assert.doesNotMatch(source, /测试用例审阅|Test Case Revision|caseRevisions|sourceSelection/u)
  assert.doesNotMatch(source, /最多\s*[12]\s*次/u)
})

test('正式 Requirement Release 前端类型必填且展示不回退到分析候选', () => {
  const source = read('../src/RequirementAnalysisPageV2.tsx')
  const analysisApi = read('../src/requirement-analysis-api.ts')
  assert.match(analysisApi, /export type RequirementReleasePackage = \{[\s\S]*?\n  content: \{/u)
  assert.doesNotMatch(analysisApi, /export type RequirementReleasePackage = \{[\s\S]*?\n  content\?: \{/u)
  assert.doesNotMatch(source, /release\.content\?\./u)
  assert.doesNotMatch(source, /release\.content[^\n]*\?\?\s*result\./u)
  assert.match(source, /Requirement Release 数据不完整/u)
  assert.match(source, /if \(!result && !release\)/u)
  assert.match(source, /const candidateArtifacts = release \? \[\] : result\?\.artifacts \?\? \[\]/u)
})

test('同一 TestDesign 展示运行历史并以选中 runId 切换完整工作区', () => {
  const page = read('../src/test-design/TestDesignPage.tsx')
  const hook = read('../src/test-design/hooks/useTestDesign.ts')
  const api = read('../src/test-design/api.ts')
  for (const label of ['运行历史', '新建运行', '状态 / 阶段', '历史基线', '已发布', '未发布']) assert.match(page, new RegExp(label, 'u'))
  assert.match(page, /model\.openRun\(item\.id\)/u)
  assert.match(page, /linkedOpenedTargetId\.current === linkedTargetId/u)
  assert.doesNotMatch(page, /\[linkedDesignId, linkedRunId, linkedTargetId, model\.design\?\.id, model\.run\?\.id/u)
  assert.match(hook, /api\.loadRuns/u)
  assert.match(hook, /api\.loadRun\(projectVersionId, design\.id, runId\)/u)
  assert.match(api, /test-designs\/\$\{encodeURIComponent\(designId\)\}\/runs/u)
})

test('测试用例支持新增、结构化编辑、单条审核与 Revision 记录', () => {
  const panel = read('../src/test-design/TestCasePanel.tsx')
  const page = read('../src/test-design/TestDesignPage.tsx')
  const styles = read('../src/test-design/test-design.css')
  const hook = read('../src/test-design/hooks/useTestDesign.ts')
  const service = read('../server/application/test-design-service.ts')
  for (const label of ['新增', 'Candidate Delta 审核', '批量审核', '提交审核', '退回修改', '拒绝', '前置条件', '执行步骤', '预期结果', '扩展测试']) assert.match(panel, new RegExp(label, 'u'))
  assert.match(panel, /TestCase v3/u)
  assert.match(styles, /\.tdw-embedded\{[^}]*--td2-blue:#3157d5/u)
  assert.doesNotMatch(panel, /executionSpec|uiSpec|apiSpec|dataRequirements/u)
  assert.match(service, /TEST_CASE_EDIT_REVIEW_STATE_INVALID/u)
  assert.match(service, /TEST_CASE_REVIEW_COMMENT_REQUIRED/u)
  assert.match(service, /function newCase[^\n]+reviewState: 'in_review'/u)
  assert.match(service, /draft: \{ submit: 'in_review' \}/u)
  assert.match(service, /testCase\.reviewState = 'draft'/u)
  assert.match(page, /className=\{tab === item\.key \? 'tdw-tab-active' : ''\}/u)
  assert.match(styles, /\.tdw-embedded>\.tdw-tabs>button\.tdw-tab-active/u)
  for (const method of ['createCase', 'patchCase', 'deleteCase', 'reviewCase']) assert.match(hook, new RegExp(`api\\.${method}`, 'u'))
})

test('测试执行与报告诊断均使用真实懒加载页面', () => {
  const app = read('../src/App.tsx')
  const page = read('../src/test-execution/TestExecutionPage.tsx')
  const runPanel = read('../src/test-execution/ExecutionRunPanel.tsx')
  const taskPanel = read('../src/test-execution/ExecutionTaskPanel.tsx')
  const hook = read('../src/test-execution/hooks/useTestExecution.ts')
  const api = read('../src/test-execution/api.ts')
  const readme = read('../README.md')
  assert.match(app, /\.\/test-execution\/TestExecutionPage/u)
  assert.match(app, /正在加载测试执行工作台/u)
  assert.doesNotMatch(app, /测试执行[^\n]+hint: '占位'/u)
  assert.match(app, /\.\/test-report\/TestReportPage/u)
  assert.match(app, /正在加载报告与诊断工作台/u)
  assert.doesNotMatch(app, /报告与诊断[^\n]+hint: '占位'/u)
  for (const boundary of ['PostgreSQL', 'AgentRunner', 'Agent Under Test', 'FailureAnalysis']) assert.match(`${page}\n${runPanel}`, new RegExp(boundary, 'u'))
  for (const history of ['Repeat', 'Assertions', 'Evaluations', 'Trace', '失败分析']) assert.match(taskPanel, new RegExp(history, 'u'))
  for (const removed of ['Artifact Store', 'ScriptRevision', 'ExecutionEventTimeline', 'Playwright Reporter', 'artifactUrl']) assert.doesNotMatch(`${page}\n${runPanel}\n${taskPanel}\n${api}`, new RegExp(removed, 'u'))
  assert.match(api, /JSON\.stringify\(\{ agentUnderTestId \}\)/u)
  for (const contract of ['创建 Agent Test Run', 'Agent Under Test', 'Endpoint', 'type="url"']) assert.match(runPanel, new RegExp(contract, 'u'))
  assert.doesNotMatch(api, /JSON\.stringify\(\{[^}]*mode/u)
  assert.doesNotMatch(`${page}\n${runPanel}\n${taskPanel}\n${hook}`, /Math\.random|setInterval|fakeArtifact|mockProgress/u)
  assert.match(hook, /window\.setTimeout\(poll, 1800\)/u)
  assert.match(readme, /当前测试执行只保留 Agent Test 主链/u)
  assert.match(readme, /agent-test-execution-report\/v2/u)
  assert.doesNotMatch(readme, /第一期-项目知识库|第二期-需求评审/u)
  assert.equal(existsSync(new URL('../_temp.patch', import.meta.url)), false)
})

test('Coverage 面板只展示确定性 v3 审计，发布面板突出正式发布状态', () => {
  const audit = read('../src/test-design/CoverageAuditPanel.tsx')
  const publish = read('../src/test-design/TestDesignPublicationPanel.tsx')
  const runPanel = read('../src/test-design/TestDesignRunPanel.tsx')
  assert.match(audit, /resolution=agent_repair/u)
  assert.match(audit, /automaticRepair\.maxAttempts/u)
  assert.match(audit, /automaticRepair\.attempt/u)
  assert.doesNotMatch(audit, /maxAttempts\s*\?\?\s*[12]/u)
  assert.doesNotMatch(runPanel, /最多\s*[12]\s*次/u)
  assert.match(runPanel, /PlanningAgent · 自动修复/u)
  assert.match(audit, /Effective Case Set/u)
  assert.match(audit, /coverageTarget Requirement/u)
  assert.match(audit, /coverageAudits\.at\(-1\)/u)
  assert.match(publish, /Coverage Audit/u)
  assert.match(publish, /正式用例库已发布/u)
  assert.doesNotMatch(publish, /Workspace 投影待处理/u)
  assert.match(publish, /contentSha256/u)
  assert.match(publish, /publicationAuditBlockers/u)
  assert.doesNotMatch(publish, /find\(item => item\.status === 'valid'\)/u)
  assert.match(runPanel, /not_needed · 无 agent_repair 阻断项/u)
})

test('历史用例库版本、套件和发布记录全部使用冻结 Revision', () => {
  const suite = read('../src/test-design/TestSuiteLibraryPanel.tsx')
  const library = read('../src/test-design/TestCaseLibraryPanel.tsx')
  const publish = read('../src/test-design/TestDesignPublicationPanel.tsx')
  const api = read('../src/test-design/api.ts')
  assert.match(suite, /member\.frozenContent\.title/u)
  assert.match(suite, /methodsForContent\(member\.frozenContent\)/u)
  assert.match(suite, /该用例已有较新 Revision，当前套件仍使用冻结的 Revision/u)
  assert.match(library, /suiteMemberInput\(id, member\.frozenContent/u)
  assert.doesNotMatch(library, /executionMethod\(testCase\.content\).*批量加入/u)
  assert.match(library, /Revision 原始追溯/u)
  assert.match(library, /currentRevision\?\.traceability/u)
  assert.match(library, /Library Version Member 当前版本追溯/u)
  assert.match(library, /member\.traceability/u)
  assert.match(library, /扩展测试 \/ 当前版本无 Requirement direct trace/u)
  assert.doesNotMatch(library, /<h4>需求追溯<\/h4>/u)
  assert.match(publish, /冻结内容 Hash/u)
  assert.match(publish, /冻结 Revision r/u)
  assert.match(publish, /memberMethods/u)
})

test('测试设计页面在窄视口收敛布局并允许长 Hash 与路径完整显示', () => {
  const styles = read('../src/test-design/test-design.css')
  assert.match(styles, /@media \(max-width:760px\)/u)
  assert.match(styles, /min-width:0/u)
  assert.match(styles, /overflow-wrap:anywhere/u)
  assert.match(styles, /text-overflow:ellipsis/u)
  assert.match(styles, /overflow-x:auto/u)
})
