import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

test('测试设计页面拆分为固定流程面板且不展示多 Agent DAG', () => {
  const page = read('../src/test-design/TestDesignPage.tsx')
  for (const panel of ['TestDesignCreatePanel', 'TestDesignRunPanel', 'TestPointReviewPanel', 'TestCasePanel', 'CaseChangeProposalPanel', 'CoverageAuditPanel', 'TestDesignPublicationPanel', 'TestCaseLibraryPanel', 'TestSuiteLibraryPanel']) assert.match(page, new RegExp(panel, 'u'))
  for (const entry of ['设计任务', '测试用例库', '测试套件', '发布记录']) assert.match(page, new RegExp(entry, 'u'))
  assert.doesNotMatch(page, /ExecutionHandoffPanel/u)
  assert.doesNotMatch(page, /TestAnalysisAgent|FunctionalTestDesignAgent|NonFunctionalTestDesignAgent|TestCaseSynthesisAgent|scope_gate|tree_merge/u)
  assert.match(read('../src/RequirementAnalysisPageV2.tsx'), /\.\/test-design\/TestDesignPage/u)
})

test('需求分析页面只在当前选择的成功 Requirement Release Run 上开放测试设计，新建对话仍须先分析', () => {
  const source = read('../src/RequirementAnalysisPageV2.tsx')
  assert.match(source, /const releaseBindings = projectVersion\?\.requirementReleaseBindings/u)
  assert.match(source, /const selectedReleaseBinding = selectedRun \? releaseBindings\.find/u)
  assert.match(source, /const testDesignReady = Boolean\(selectedRun && selectedReleaseBinding/u)
  assert.match(source, /const selectedRun = runs\.find\(run => run\.id === selectedRunId\)/u)
  assert.match(source, /<option value="">新建对话<\/option>/u)
  assert.match(source, /新建对话（未创建 Run）/u)
  assert.match(source, /本次需求分析尚未发布/u)
  assert.match(source, /请先完成需求分析/u)
  assert.match(source, /loadRun as loadTestDesignRun/u)
  assert.match(source, /<TestDesignConversationEntry linkage=\{linkedTestDesign\}/u)
  assert.match(source, /测试点设计/u)
  assert.match(source, /测试设计已停止/u)
})

test('创建面板明确展示绑定需求发布包并定义范围、维度和执行入口', () => {
  const source = read('../src/test-design/TestDesignCreatePanel.tsx')
  assert.match(source, /Requirement Release/u)
  assert.match(source, /requirementReleases/u)
  assert.match(source, /requirementReleaseId/u)
  assert.match(source, /releaseId/u)
  assert.match(source, /纳入范围/u)
  assert.match(source, /排除范围/u)
  assert.match(source, /测试维度/u)
  assert.match(source, /执行入口/u)
  assert.doesNotMatch(source, /basisMode|review_baseline|sourceTechnicalSolutionRunId/u)
})

test('运行面板展示冻结 Release、Workspace、Agent 配置与实时轨迹', () => {
  const source = read('../src/test-design/TestDesignRunPanel.tsx')
  assert.match(source, /Requirement Release/u)
  assert.match(source, /verificationRunId/u)
  assert.match(source, /requirementsJsonSha256/u)
  assert.match(source, /Workspace Snapshot/u)
  assert.match(source, /Agent 配置快照/u)
  assert.match(source, /Pi Agent 实时轨迹/u)
  assert.match(source, /Skill 已读取/u)
  assert.match(source, /skillKey/u)
  assert.match(source, /Coverage 检查/u)
})

test('测试点由服务端自动校验并保留树操作与 AI 重新设计', () => {
  const review = read('../src/test-design/TestPointReviewPanel.tsx')
  const tree = read('../src/test-design/TestPointTreePanel.tsx')
  assert.match(review, /服务端自动校验/u)
  assert.match(review, /不需要人工批准/u)
  assert.match(review, /自动校验通过/u)
  assert.match(review, /AI 重新设计/u)
  for (const operation of ["op: 'add'", "op: 'rename'", "op: 'delete'", "op: 'split'", "op: 'merge'"]) assert.match(`${review}\n${tree}`, new RegExp(operation, 'u'))
  assert.match(review, /op: 'update'/u)
  assert.match(review, /Revision 修改说明/u)
  assert.match(review, /执行入口/u)
  assert.doesNotMatch(`${review}\n${tree}`, /window\.(?:prompt|confirm)/u)
})

test('测试用例支持新增、结构化编辑、单条审核与 Revision 记录', () => {
  const panel = read('../src/test-design/TestCasePanel.tsx')
  const hook = read('../src/test-design/hooks/useTestDesign.ts')
  for (const label of ['新增用例', '编辑并新建 Revision', '要求修改', 'Revision 与审核记录', '确认删除']) assert.match(panel, new RegExp(label, 'u'))
  assert.match(panel, /执行步骤/u)
  assert.match(panel, /关联可执行测试点/u)
  for (const method of ['createCase', 'patchCase', 'deleteCase', 'reviewCase']) assert.match(hook, new RegExp(`api\\.${method}`, 'u'))
})

test('测试执行与报告诊断均使用真实懒加载页面', () => {
  const app = read('../src/App.tsx')
  const page = read('../src/test-execution/TestExecutionPage.tsx')
  const runPanel = read('../src/test-execution/ExecutionRunPanel.tsx')
  const taskPanel = read('../src/test-execution/ExecutionTaskPanel.tsx')
  const hook = read('../src/test-execution/hooks/useTestExecution.ts')
  const api = read('../src/test-execution/api.ts')
  const readme = read('../README.md')
  assert.match(app, /\.\/test-execution\/TestExecutionPage/u)
  assert.match(app, /正在加载测试执行工作台/u)
  assert.doesNotMatch(app, /测试执行[^\n]+hint: '占位'/u)
  assert.match(app, /\.\/test-report\/TestReportPage/u)
  assert.match(app, /正在加载报告与诊断工作台/u)
  assert.doesNotMatch(app, /报告与诊断[^\n]+hint: '占位'/u)
  for (const boundary of ['TestExecutionHandoff', 'PostgreSQL', 'Artifact Store', 'OCI Runner']) assert.match(`${page}\n${runPanel}`, new RegExp(boundary, 'u'))
  for (const history of ['Runner Attempts', 'Same-script retries', 'Automatic repairs', '诊断', '脚本 Revision', 'Artifacts']) assert.match(taskPanel, new RegExp(history, 'u'))
  assert.match(api, /JSON\.stringify\(\{ handoffId, environmentId \}\)/u)
  assert.doesNotMatch(api, /JSON\.stringify\(\{[^}]*mode/u)
  assert.doesNotMatch(`${page}\n${runPanel}\n${taskPanel}\n${hook}`, /Math\.random|setInterval|fakeArtifact|mockProgress/u)
  assert.match(hook, /window\.setTimeout\(poll, 1800\)/u)
  assert.match(readme, /\| 测试执行 \| 已实现 \|/u)
  assert.match(readme, /\| 报告与诊断 \| 已实现 \|/u)
  assert.doesNotMatch(readme, /第一期-项目知识库|第二期-需求评审/u)
  assert.equal(existsSync(new URL('../_temp.patch', import.meta.url)), false)
})

test('Coverage 面板区分 Agent Repair 与 Human Decision，发布面板显示正式资产文件', () => {
  const audit = read('../src/test-design/CoverageAuditPanel.tsx')
  const publish = read('../src/test-design/TestDesignPublicationPanel.tsx')
  assert.match(audit, /resolution=agent_repair/u)
  assert.match(audit, /最多/u)
  assert.match(audit, /等待人工决策/u)
  assert.match(publish, /Coverage Audit/u)
  assert.match(publish, /Workspace 投影/u)
  assert.match(publish, /contentSha256/u)
  assert.match(publish, /Execution Handoff/u)
})

test('历史用例库版本、套件批量选择与 Handoff 全部使用冻结 Revision', () => {
  const suite = read('../src/test-design/TestSuiteLibraryPanel.tsx')
  const library = read('../src/test-design/TestCaseLibraryPanel.tsx')
  const publish = read('../src/test-design/TestDesignPublicationPanel.tsx')
  const api = read('../src/test-design/api.ts')
  assert.match(suite, /member\.frozenContent\.title/u)
  assert.match(suite, /member\.frozenContent\.executionSpec/u)
  assert.match(suite, /该用例已有较新 Revision，当前套件仍使用冻结的 Revision/u)
  assert.match(library, /executionMethod\(member\.frozenContent\)/u)
  assert.doesNotMatch(library, /executionMethod\(testCase\.content\).*批量加入/u)
  assert.match(publish, /冻结内容 Hash/u)
  assert.match(publish, /needs_confirmation 成员默认被服务端阻断/u)
  assert.match(publish, /人工覆盖原因（必填）/u)
  assert.match(publish, /overrideInputs\.some\(item => !item\.reason\)/u)
  assert.match(api, /executionReadinessOverrides/u)
})

test('测试设计页面在窄视口收敛布局并允许长 Hash 与路径完整显示', () => {
  const styles = read('../src/test-design/test-design.css')
  assert.match(styles, /@media \(max-width:760px\)/u)
  assert.match(styles, /min-width:0/u)
  assert.match(styles, /overflow-wrap:anywhere/u)
  assert.match(styles, /text-overflow:ellipsis/u)
  assert.match(styles, /overflow-x:auto/u)
})
