import { Bot, CheckCircle2, Clock3, Database, Play, RefreshCw, Server, ShieldAlert, Square } from 'lucide-react'
import { useState } from 'react'
import type { AgentUnderTest, ExecutionReadiness, ExecutionRun, Versioned } from './types'

export function ExecutionRunPanel({ readiness, agentsUnderTest, runs, run, busy, loading, onRefresh, onCreate, onCreateAgentUnderTest, onOpen, onCancel }: {
  readiness: ExecutionReadiness | null; agentsUnderTest: AgentUnderTest[]; runs: ExecutionRun[]; run: Versioned<ExecutionRun> | null
  busy: string; loading: boolean; onRefresh: () => Promise<void>; onCreate: (id: string) => Promise<ExecutionRun | undefined>
  onCreateAgentUnderTest: (input: Parameters<typeof import('./api').createAgentUnderTest>[1]) => Promise<AgentUnderTest | undefined>
  onOpen: (id: string) => Promise<ExecutionRun | undefined>; onCancel: () => Promise<void>
}) {
  const [agentUnderTestId, setAgentUnderTestId] = useState('')
  const [showForm, setShowForm] = useState(false)
  const [draft, setDraft] = useState({ name: '', endpoint: '', protocol: 'http' as 'http' | 'sse', inputField: 'input', outputPath: 'output', tracePath: 'trace' })
  const selectedAgent = agentsUnderTest.find(item => item.id === agentUnderTestId)
  return <div className="te-run-column">
    <section className="te-card te-readiness"><header><div><h2>Agent Test 就绪状态</h2><p>只检查 PostgreSQL、AgentRunner 与失败分析 Agent。</p></div><button className="te-icon-button" disabled={loading} onClick={() => void onRefresh()}><RefreshCw /></button></header><div className="te-readiness-grid"><ReadinessItem icon={<Database />} label="PostgreSQL" ready={readiness?.store.ready} reason={readiness?.store.reason} /><ReadinessItem icon={<Server />} label="AgentRunner" ready={readiness?.runner.ready} /><ReadinessItem icon={<Bot />} label="FailureAnalysis" ready={readiness?.agent.ready} reason={readiness?.agent.reason} /></div></section>
    <section className="te-card te-create-card"><header><div><h2>创建 Agent Test Run</h2><p>冻结正式 Agent Case、被测 Agent 版本与平台诊断配置。</p></div></header><label>Agent Under Test<select value={agentUnderTestId} onChange={event => setAgentUnderTestId(event.target.value)}><option value="">选择被测 Agent</option>{agentsUnderTest.filter(item => item.enabled).map(item => <option key={item.id} value={item.id}>{item.name} · V{item.currentVersion}</option>)}</select><small>{selectedAgent ? selectedAgent.versions.find(item => item.version === selectedAgent.currentVersion)?.endpoint : '凭据只通过环境变量引用。'}</small></label><button className="te-secondary" onClick={() => setShowForm(value => !value)}>{showForm ? '收起配置' : '新增被测 Agent'}</button>
      {showForm && <div className="te-agent-under-test-form"><label>名称<input value={draft.name} onChange={event => setDraft(value => ({ ...value, name: event.target.value }))} /></label><label>Endpoint<input type="url" value={draft.endpoint} onChange={event => setDraft(value => ({ ...value, endpoint: event.target.value }))} /></label><label>协议<select value={draft.protocol} onChange={event => setDraft(value => ({ ...value, protocol: event.target.value as 'http' | 'sse' }))}><option value="http">HTTP</option><option value="sse">SSE</option></select></label><label>Input 字段<input value={draft.inputField} onChange={event => setDraft(value => ({ ...value, inputField: event.target.value }))} /></label><label>Output Path<input value={draft.outputPath} onChange={event => setDraft(value => ({ ...value, outputPath: event.target.value }))} /></label><label>Trace Path<input value={draft.tracePath} onChange={event => setDraft(value => ({ ...value, tracePath: event.target.value }))} /></label><button className="te-secondary" disabled={!draft.name.trim() || !draft.endpoint.trim() || Boolean(busy)} onClick={() => void onCreateAgentUnderTest({ name: draft.name, endpoint: draft.endpoint, protocol: draft.protocol, authenticationConfig: { type: 'none' }, requestMapping: { method: 'POST', inputField: draft.inputField }, responseMapping: { outputPath: draft.outputPath, ...(draft.tracePath ? { tracePath: draft.tracePath } : {}), traceCompleteness: 'partial' }, documentationRefs: [] }).then(created => { if (created) { setAgentUnderTestId(created.id); setShowForm(false) } })}>保存被测 Agent</button></div>}
      <button className="te-primary" disabled={!readiness?.ready || !agentUnderTestId || Boolean(busy)} onClick={() => void onCreate(agentUnderTestId)}><Play />{busy === 'create' ? '创建中…' : '创建 Agent Test Run'}</button>
    </section>
    <section className="te-card te-run-history"><header><div><h2>Agent Test 历史</h2><p>PostgreSQL 正式 Run。</p></div><span>{runs.length}</span></header><div className="te-run-list">{runs.map(item => <button key={item.id} className={run?.value.id === item.id ? 'active' : ''} onClick={() => void onOpen(item.id)}><StatusMark status={item.status} /><span><b>{item.agentUnderTest.name} · {item.taskCount} Tasks</b><small>{new Date(item.createdAt).toLocaleString('zh-CN')}</small><code>{shortId(item.id)}</code></span><em className={`te-status-pill ${item.status}`}>{runStatusLabel(item.status)}</em></button>)}{!runs.length && !loading && <p className="te-empty">暂无 Agent Test 历史</p>}</div></section>
    {run && <section className="te-card te-run-snapshot"><header><div><h2>本次执行</h2><p>冻结的 Agent Test 正式事实。</p></div>{['queued', 'running'].includes(run.value.status) && <button className="te-danger" disabled={Boolean(busy) || Boolean(run.value.cancelRequestedAt)} onClick={() => void onCancel()}><Square />取消</button>}</header><dl><div><dt>被测 Agent</dt><dd>{run.value.agentUnderTest.name} · V{run.value.agentUnderTest.version}</dd></div><div><dt>协议</dt><dd>{run.value.agentUnderTest.protocol.toUpperCase()}</dd></div><div><dt>Runner</dt><dd>{run.value.runner.runnerVersion}</dd></div><div><dt>用例库</dt><dd>{shortId(run.value.handoff.testCaseLibraryVersionId)}</dd></div><div><dt>失败分析</dt><dd>V{run.value.agents.failureAnalysis.configurationVersion}</dd></div></dl></section>}
  </div>
}
function ReadinessItem({ icon, label, ready, reason }: { icon: React.ReactNode; label: string; ready?: boolean; reason?: string }) { return <div className={ready ? 'ready' : 'unavailable'}>{icon}<span><b>{label}</b><small>{ready ? 'Ready' : reason ?? '未就绪'}</small></span>{ready ? <CheckCircle2 /> : <ShieldAlert />}</div> }
function StatusMark({ status }: { status: ExecutionRun['status'] }) { return status === 'succeeded' ? <CheckCircle2 /> : ['queued', 'running'].includes(status) ? <Clock3 /> : <ShieldAlert /> }
export function runStatusLabel(status: ExecutionRun['status']) { return ({ queued: '排队中', running: '执行中', succeeded: '成功', failed: '失败', partial: '部分完成', cancelled: '已取消' })[status] }
export function shortId(value: string) { return value.length > 18 ? `${value.slice(0, 10)}…${value.slice(-6)}` : value }
