import { Check, CopyCheck, FileDiff, Pencil, RotateCcw, ShieldX, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { actualExecutionMethod, executionPendingItems, TestCaseEditor, testCaseEditorValid } from './TestCaseEditor'
import type { CaseChangeDecision, CaseChangeOperation, CaseChangeProposal, TestCaseContent, TestDesignWorkflowRun } from './types'

const filters: Array<{ key: 'all' | CaseChangeOperation; label: string }> = [{ key: 'all', label: '全部' }, { key: 'reuse', label: '复用' }, { key: 'update', label: '修改' }, { key: 'create', label: '新增' }, { key: 'deprecate', label: '废弃' }, { key: 'reference', label: '仅参考' }]

export function CaseChangeProposalPanel({ run, busy, onDecision, onBatchAccept }: { run: TestDesignWorkflowRun; busy: boolean; onDecision: (proposalId: string, decision: Exclude<CaseChangeDecision, 'pending'>, comment?: string, editedContent?: TestCaseContent) => Promise<void>; onBatchAccept: (targets: Array<{ proposalId: string; expectedVersion: number }>) => Promise<void> }) {
  const [filter, setFilter] = useState<(typeof filters)[number]['key']>('all')
  const proposals = useMemo(() => run.caseChangeProposals.filter(item => filter === 'all' || item.operation === filter), [filter, run.caseChangeProposals])
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const selected = proposals.find(item => item.id === selectedId) ?? proposals[0]
  const [editing, setEditing] = useState<CaseChangeProposal | null>(null)
  const [confirmingBatchAccept, setConfirmingBatchAccept] = useState(false)
  const batchEligible = useMemo(() => run.caseChangeProposals.filter(item => isBatchAcceptEligible(run, item)), [run])
  return <section className="tdw-panel tdw-proposals"><header><div><span className="tdw-icon"><FileDiff /></span><div><h2>历史用例变更</h2><p>AI 只提交建议；正式用例标识、修订版本与发布状态均由服务端在人工处置后生成。</p></div></div><div className="tdw-proposal-header-actions">{batchEligible.length > 0 && <button className="td2-button primary" disabled={busy} onClick={() => setConfirmingBatchAccept(true)}><Check />批量接受未变化复用（{batchEligible.length}）</button>}<span className="tdw-badge">待处置 {run.caseChangeProposals.filter(item => item.decision === 'pending').length}</span></div></header>
    <nav className="tdw-filter-tabs">{filters.map(item => <button key={item.key} className={filter === item.key ? 'active' : ''} onClick={() => { setFilter(item.key); setSelectedId(null) }}>{item.label}<i>{run.caseChangeProposals.filter(proposal => item.key === 'all' || proposal.operation === item.key).length}</i></button>)}</nav>
    {!proposals.length ? <div className="tdw-empty"><CopyCheck /><b>当前筛选没有 Proposal</b><span>候选用例生成完成后，会在这里展示复用、修改、新增、废弃和参考建议。</span></div> : <div className="tdw-master-detail"><div className="tdw-master-list">{proposals.map(item => <button key={item.id} className={selected?.id === item.id ? 'active' : ''} onClick={() => setSelectedId(item.id)}><span className={`tdw-operation ${item.operation}`}>{operationLabel(item.operation)}</span><b>{item.candidateContent?.title ?? item.sourceCaseId ?? item.id}</b><small>{item.reason}</small><footer><code>{item.sourceCaseId ? `${item.sourceCaseId} · r${item.sourceRevision}` : '新 Case ID'}</code><em className={item.decision}>{decisionLabel(item.decision)}</em></footer></button>)}</div>{selected && <ProposalDetail proposal={selected} busy={busy} onEdit={() => setEditing(selected)} onDecision={(decision, comment) => onDecision(selected.id, decision, comment)} />}</div>}
    {editing && <EditProposalDialog proposal={editing} busy={busy} onClose={() => setEditing(null)} onSave={(content, comment) => onDecision(editing.id, 'accepted_edited', comment, content)} />}
    {confirmingBatchAccept && <div className="tdw-backdrop"><section className="tdw-modal"><header><div><Check /><span><b>批量接受未变化复用</b><small>仅接受与来源 Revision 语义完全一致、未经过人工编辑或 Agent Patch 修改的 reuse Proposal。</small></span></div><button onClick={() => setConfirmingBatchAccept(false)}><X /></button></header><p>本次将接受 <b>{batchEligible.length}</b> 条未变化复用 Proposal。每一条都会由 Service 记录正式审核决策；新增、修改、废弃和仅参考 Proposal 不会受影响。</p><footer><button onClick={() => setConfirmingBatchAccept(false)}>取消</button><button className="primary" disabled={busy} onClick={() => { void onBatchAccept(batchEligible.map(item => ({ proposalId: item.id, expectedVersion: item.decisions.length }))).then(() => setConfirmingBatchAccept(false)).catch(() => undefined) }}>确认接受 {batchEligible.length} 条</button></footer></section></div>}
  </section>
}

function ProposalDetail({ proposal, busy, onEdit, onDecision }: { proposal: CaseChangeProposal; busy: boolean; onEdit: () => void; onDecision: (decision: Exclude<CaseChangeDecision, 'pending'>, comment?: string) => Promise<void> }) {
  return <article className="tdw-proposal-detail"><header><div><span className={`tdw-operation ${proposal.operation}`}>{operationLabel(proposal.operation)}</span><h3>{proposal.candidateContent?.title ?? proposal.sourceCaseId ?? '变更建议'}</h3></div><strong>{Math.round(proposal.confidence * 100)}% 置信度</strong></header>
    <div className="tdw-proposal-kpis"><span><small>历史 Revision</small><b>{proposal.sourceCaseId ? `${proposal.sourceCaseId} / r${proposal.sourceRevision}` : '无（新增）'}</b></span><span><small>关联需求变化</small><b>{proposal.requirementRefs.length || '未标注'}</b></span></div>
    <section><h4>Agent 修改理由</h4><p>{proposal.reason}</p></section>
    <section><h4>字段级 Diff</h4>{proposal.diff.length ? <div className="tdw-diff-list">{proposal.diff.map((change, index) => <article key={`${change.path}-${index}`}><code>{change.path}</code><div><pre>{format(change.before)}</pre><span>→</span><pre>{format(change.after)}</pre></div></article>)}</div> : <p className="tdw-muted">内容未变化，复用原 Case ID 与 Revision。</p>}</section>
    <section><h4>自动化脚本影响</h4><p>{automationImpact(proposal)}</p></section>
    <section><h4>建议内容与执行配置</h4>{proposal.candidateContent ? <><div className="tdw-chips"><span>{proposal.candidateContent.dimension}</span><span>{actualExecutionMethod(proposal.candidateContent)}</span><span>{proposal.candidateContent.executionSpec?.executionReadiness ?? 'needs_confirmation'}</span></div><pre className="tdw-json">{JSON.stringify(proposal.candidateContent.executionSpec, null, 2)}</pre>{executionPendingItems(proposal.candidateContent).map(item => <p className="td-confirmation-note" key={item}>待确认：{item}</p>)}</> : <p className="tdw-muted">该 Proposal 不包含候选内容。</p>}</section>
    <footer className="tdw-actions">{proposal.decision === 'pending' ? <><button disabled={busy || proposal.operation === 'deprecate' || proposal.operation === 'reference'} className="primary" onClick={() => void onDecision('accepted').catch(() => undefined)}><Check />接受建议</button><button disabled={busy || !proposal.candidateContent || proposal.operation === 'deprecate' || proposal.operation === 'reference'} onClick={onEdit}><Pencil />编辑后接受</button>{proposal.sourceCaseId && <button disabled={busy} onClick={() => void onDecision('keep_original').catch(() => undefined)}><RotateCcw />保留原用例</button>}<button disabled={busy} onClick={() => void onDecision('reference').catch(() => undefined)}><CopyCheck />标记仅参考</button>{proposal.operation === 'deprecate' && <button disabled={busy} className="danger" onClick={() => void onDecision('deprecated').catch(() => undefined)}><ShieldX />确认废弃</button>}<button disabled={busy} className="danger ghost" onClick={() => void onDecision('rejected').catch(() => undefined)}><X />拒绝建议</button></> : <span className={`tdw-decision ${proposal.decision}`}><Check />已处置：{decisionLabel(proposal.decision)}</span>}</footer>
  </article>
}

function EditProposalDialog({ proposal, busy, onClose, onSave }: { proposal: CaseChangeProposal; busy: boolean; onClose: () => void; onSave: (content: TestCaseContent, comment: string) => Promise<void> }) {
  const [value, setValue] = useState<TestCaseContent>(() => structuredClone(proposal.candidateContent!)); const [comment, setComment] = useState('基于 Agent 建议人工修订后接受')
  return <div className="tdw-backdrop"><section className="tdw-modal wide"><header><div><Pencil /><span><b>编辑后接受历史用例变更</b><small>保存后候选用例会生成新 Revision，并自动重新执行覆盖检查。</small></span></div><button onClick={onClose}><X /></button></header><TestCaseEditor value={value} onChange={setValue} /><label>修改说明<input value={comment} onChange={event => setComment(event.target.value)} /></label><footer><button onClick={onClose}>取消</button><button className="primary" disabled={busy || !comment.trim() || !testCaseEditorValid(value)} onClick={() => { void onSave(value, comment.trim()).then(onClose).catch(() => undefined) }}>保存并接受</button></footer></section></div>
}

function operationLabel(value: CaseChangeOperation) { return ({ reuse: '复用', update: '修改', create: '新增', deprecate: '废弃', reference: '仅参考' } as const)[value] }
function isBatchAcceptEligible(run: TestDesignWorkflowRun, proposal: CaseChangeProposal) { const candidate = proposal.candidateCaseId ? run.testCases.find(item => item.id === proposal.candidateCaseId && !item.tombstonedAt) : undefined; return proposal.operation === 'reuse' && proposal.decision === 'pending' && proposal.diff.length === 0 && candidate?.origin === 'historical_unchanged' && candidate.reviewActions.length === 0 }
function decisionLabel(value: CaseChangeDecision) { return ({ pending: '待处置', accepted: '已接受', accepted_edited: '编辑后接受', rejected: '已拒绝', keep_original: '保留原用例', reference: '仅参考', deprecated: '已废弃' } as const)[value] }
function automationImpact(proposal: CaseChangeProposal) { if (proposal.operation === 'reuse') return '复用相同 Revision，不要求复制或重建自动化脚本。'; if (proposal.operation === 'update') return 'Case ID 保持稳定，但字段变化可能影响步骤、定位器、断言或测试数据，执行侧应按新 Revision 评估脚本。'; if (proposal.operation === 'deprecate') return '历史脚本和执行记录继续关联原 Case ID，但该用例不进入新版本。'; if (proposal.operation === 'create') return '新增 Case ID，后续可为该 Revision 创建新的自动化实现。'; return '仅用于设计参考，不进入本次正式版本，也不触发脚本变更。' }
function format(value: unknown) { return value === undefined ? '∅' : typeof value === 'string' ? value : JSON.stringify(value, null, 2) }
