import { Archive, Check, Copy, FileClock, Filter, Layers3, Pencil, Plus, Save, Search, TestTube2, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import * as api from './api'
import { createEmptyTestCase, TestCaseEditor, testCaseEditorValid } from './TestCaseEditor'
import type { LibraryTestCase, LibraryTestSuiteVersion, TestCaseContent, TestCaseLibraryVersion, TestCaseTraceability, TestExecutionMethod, TestSuiteDraft } from './types'

type SuiteValue = { suiteKey: string; suiteType: 'smoke' | 'regression' | 'custom'; name: string; testCaseLibraryVersionId: string; members: Array<{ caseId: string; executionMethod: TestExecutionMethod; reason: string }> }

export function TestCaseLibraryPanel({ projectId, cases, versions, suiteDrafts, suiteVersions, busy, onCreate, onEdit, onCopy, onDeprecate, onSaveSuite }: { projectId: string; cases: LibraryTestCase[]; versions: TestCaseLibraryVersion[]; suiteDrafts: TestSuiteDraft[]; suiteVersions: LibraryTestSuiteVersion[]; busy: boolean; onCreate: (content: TestCaseContent, reason: string) => void; onEdit: (testCase: LibraryTestCase, content: TestCaseContent, reason: string, traceability?: TestCaseTraceability) => void; onCopy: (testCase: LibraryTestCase) => void; onDeprecate: (testCase: LibraryTestCase, reason: string) => void; onSaveSuite: (draft: TestSuiteDraft, value: SuiteValue) => void }) {
  const [query, setQuery] = useState(''); const [dimension, setDimension] = useState(''); const [method, setMethod] = useState(''); const [priority, setPriority] = useState(''); const [status, setStatus] = useState('active'); const [tag, setTag] = useState('')
  const [selectedId, setSelectedId] = useState<string | null>(null); const [checked, setChecked] = useState<string[]>([]); const [editor, setEditor] = useState<LibraryTestCase | 'create' | null>(null); const [deprecating, setDeprecating] = useState<LibraryTestCase | null>(null)
  const filtered = useMemo(() => cases.filter(item => (!query || `${item.id} ${item.content.title} ${item.content.objective}`.toLowerCase().includes(query.toLowerCase())) && (!dimension || item.content.dimension === dimension) && (!method || executionMethod(item.content) === method) && (!priority || item.content.priority === priority) && (!status || item.status === status) && (!tag || item.content.tags.includes(tag))), [cases, dimension, method, priority, query, status, tag])
  const selected = filtered.find(item => item.id === selectedId) ?? filtered[0]
  const [detail, setDetail] = useState<LibraryTestCase | null>(null)
  useEffect(() => { setDetail(null); if (selected) void api.loadLibraryCase(projectId, selected.id).then(result => setDetail(result.value)).catch(() => setDetail(selected)) }, [projectId, selected])
  return <section className="tdw-panel tdw-library"><header><div><span className="tdw-icon"><TestTube2 /></span><div><h2>项目级正式测试用例库</h2><p>Case ID 跨项目版本稳定；修改创建新 Revision，删除统一为废弃。</p></div></div><button className="primary" onClick={() => setEditor('create')}><Plus />新增正式用例</button></header>
    <div className="tdw-library-filters"><label className="search"><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索 Case ID、标题或目标" /></label><Filter /><select value={dimension} onChange={event => setDimension(event.target.value)}><option value="">全部维度</option>{['functional', 'performance', 'stability', 'compatibility', 'security'].map(value => <option key={value}>{value}</option>)}</select><select value={method} onChange={event => setMethod(event.target.value)}><option value="">全部执行方式</option>{['ui', 'api', 'performance_tool', 'long_running', 'environment_matrix'].map(value => <option key={value}>{value}</option>)}</select><select value={priority} onChange={event => setPriority(event.target.value)}><option value="">全部优先级</option>{['P0', 'P1', 'P2', 'P3'].map(value => <option key={value}>{value}</option>)}</select><select value={status} onChange={event => setStatus(event.target.value)}><option value="">全部状态</option><option value="active">active</option><option value="deprecated">deprecated</option></select><input value={tag} onChange={event => setTag(event.target.value)} placeholder="标签精确筛选" /></div>
    <div className="tdw-batchbar"><span>已选择 <b>{checked.length}</b> 条</span><select id="tdw-suite-target" defaultValue=""><option value="">选择套件草稿</option>{suiteDrafts.filter(item => item.status === 'draft' && item.compatibilityStatus !== 'migration_required').map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!checked.length || busy} onClick={() => { const element = document.querySelector<HTMLSelectElement>('#tdw-suite-target'); const draft = suiteDrafts.find(item => item.id === element?.value); const libraryVersion = versions.find(item => item.id === draft?.testCaseLibraryVersionId); if (!draft || !libraryVersion) return; const existing = new Set(draft.members.map(item => item.caseId)); const additions = checked.filter(id => !existing.has(id)).flatMap(id => { const member = libraryVersion.members.find(item => item.caseId === id); return member ? [{ caseId: id, executionMethod: executionMethod(member.frozenContent), reason: '从正式用例库批量加入' }] : [] }); onSaveSuite(draft, { suiteKey: draft.suiteKey, suiteType: draft.suiteType, name: draft.name, testCaseLibraryVersionId: libraryVersion.id, members: [...draft.members.map(item => ({ caseId: item.caseId, executionMethod: item.executionMethod!, reason: item.reason })), ...additions] }); setChecked([]) }}><Layers3 />批量加入套件</button></div>
    {!filtered.length ? <div className="tdw-empty"><TestTube2 /><b>没有符合条件的正式用例</b><span>可调整筛选条件，或创建项目级正式用例。</span></div> : <div className="tdw-master-detail"><div className="tdw-master-list tdw-case-master">{filtered.map(item => <button key={item.id} className={selected?.id === item.id ? 'active' : ''} onClick={() => setSelectedId(item.id)}><input type="checkbox" checked={checked.includes(item.id)} onClick={event => event.stopPropagation()} onChange={() => setChecked(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])} /><span><b>{item.content.title}</b><small>{item.content.domain} · {item.content.dimension} · {executionMethod(item.content)} · {item.content.priority}</small><code>{item.id} · r{item.currentRevision}</code></span><em className={item.status}>{item.status}</em></button>)}</div>{selected && <LibraryCaseDetail testCase={detail ?? selected} suites={suiteVersions} busy={busy} onEdit={() => setEditor(detail ?? selected)} onCopy={() => onCopy(detail ?? selected)} onDeprecate={() => setDeprecating(detail ?? selected)} />}</div>}
    {editor && <LibraryCaseEditor initial={editor === 'create' ? undefined : editor} busy={busy} onClose={() => setEditor(null)} onSave={(content, reason, traceability) => { editor === 'create' ? onCreate(content, reason) : onEdit(editor, content, reason, traceability); setEditor(null) }} />}
    {deprecating && <ReasonDialog title="废弃正式测试用例" description={`将 ${deprecating.id} 标记为 deprecated；所有历史 Revision 和发布引用继续保留。`} busy={busy} submitLabel="确认废弃" onClose={() => setDeprecating(null)} onSubmit={reason => { onDeprecate(deprecating, reason); setDeprecating(null) }} />}
  </section>
}

function LibraryCaseDetail({ testCase, suites, busy, onEdit, onCopy, onDeprecate }: { testCase: LibraryTestCase; suites: LibraryTestSuiteVersion[]; busy: boolean; onEdit: () => void; onCopy: () => void; onDeprecate: () => void }) { const relatedSuites = suites.filter(suite => suite.members.some(item => item.caseId === testCase.id)); const revision = testCase.revisions?.find(item => item.revision === testCase.currentRevision); const traceability = revision?.traceability; return <article className="tdw-library-detail"><header><div><span className={`tdw-status ${testCase.status}`}>{testCase.status}</span><h3>{testCase.content.title}</h3><code>{testCase.id}</code></div><div><button disabled={busy || testCase.status === 'deprecated'} onClick={onEdit}><Pencil />编辑</button><button disabled={busy} onClick={onCopy}><Copy />复制</button><button disabled={busy || testCase.status === 'deprecated'} className="danger" onClick={onDeprecate}><Archive />废弃</button></div></header><p>{testCase.content.objective}</p><div className="tdw-proposal-kpis"><span><small>当前 Revision</small><b>r{testCase.currentRevision}</b></span><span><small>维度</small><b>{testCase.content.dimension}</b></span><span><small>执行方式</small><b>{executionMethod(testCase.content)}</b></span><span><small>优先级</small><b>{testCase.content.priority}</b></span></div><section><h4>需求追溯</h4>{traceability?.requirementRefs.length ? <div className="tdw-chips">{traceability.requirementRefs.map(item => <code key={`${item.requirementReleaseId}:${item.requirementId}`}>{item.requirementReleaseId} / {item.requirementId}</code>)}</div> : <p className="tdw-muted">历史数据未建立正式追溯</p>}</section><section><h4>测试点追溯</h4>{traceability?.testPointRefs.length ? <div className="tdw-chips">{traceability.testPointRefs.map(item => <code key={`${item.testPointTreeVersionId}:${item.testPointId}`}>{item.testPointTreeVersionId} / {item.testPointId}</code>)}</div> : <p className="tdw-muted">历史数据未建立正式追溯</p>}</section><section><h4>测试数据需求</h4>{testCase.content.dataRequirementIds.length ? <div className="tdw-chips">{testCase.content.dataRequirementIds.map(id => <code key={id}>{id}</code>)}</div> : <p className="tdw-muted">无</p>}</section><section><h4>关联测试套件</h4>{relatedSuites.length ? <div className="tdw-chips">{relatedSuites.map(item => <span key={item.id}>{item.name} V{item.version}</span>)}</div> : <p className="tdw-muted">尚未加入已发布套件。</p>}</section><section><h4>Execution Spec</h4><pre className="tdw-json">{JSON.stringify(testCase.content.executionSpec, null, 2)}</pre></section><section><h4>Revision 历史</h4><div className="tdw-revisions">{[...(testCase.revisions ?? [])].reverse().map(item => <article key={item.revision}><FileClock /><span><b>Revision {item.revision}</b><small>{item.changeReason} · {item.createdBy} · {new Date(item.createdAt).toLocaleString('zh-CN')}</small><code>{item.contentSha256}</code></span></article>)}</div></section></article> }

function LibraryCaseEditor({ initial, busy, onClose, onSave }: { initial?: LibraryTestCase; busy: boolean; onClose: () => void; onSave: (content: TestCaseContent, reason: string, traceability?: TestCaseTraceability) => void }) {
  const [content, setContent] = useState<TestCaseContent>(() => initial?.content ? structuredClone(initial.content) : createEmptyTestCase())
  const [reason, setReason] = useState(initial ? '人工维护正式用例' : '人工新增正式用例')
  const [traceabilityText, setTraceabilityText] = useState('')
  let traceability: TestCaseTraceability | undefined
  let traceabilityError = ''
  if (traceabilityText.trim()) {
    try { traceability = JSON.parse(traceabilityText) as TestCaseTraceability } catch { traceabilityError = '追溯 JSON 格式无效' }
  }
  const currentTraceability = initial?.revisions?.find(item => item.revision === initial.currentRevision)?.traceability
  return <div className="tdw-backdrop"><section className="tdw-modal wide"><header><div><Pencil /><span><b>{initial ? `编辑 ${initial.id} · 新建 Revision` : '新增正式测试用例'}</b><small>四类 executionSpec 使用结构化编辑；服务端负责 schema、Hash、Revision 与追溯门禁。</small></span></div><button onClick={onClose}><X /></button></header><TestCaseEditor value={content} onChange={setContent} /><label>变更原因<input value={reason} onChange={event => setReason(event.target.value)} /></label>{initial && <label>新 Revision 追溯（可选 JSON）<textarea value={traceabilityText} onChange={event => setTraceabilityText(event.target.value)} placeholder="普通字段修改可留空继承；修改 testPointIds、dataRequirementIds、dimension 或 objective 时必须提交完整固定追溯。" /><small>{traceabilityError || (currentTraceability ? `当前追溯：${JSON.stringify(currentTraceability)}` : '历史数据未建立正式追溯')}</small></label>}<footer><button onClick={onClose}>取消</button><button className="primary" disabled={busy || !reason.trim() || Boolean(traceabilityError) || !testCaseEditorValid(content)} onClick={() => onSave(content, reason.trim(), traceability)}><Save />保存</button></footer></section></div>
}

function ReasonDialog({ title, description, busy, submitLabel, onClose, onSubmit }: { title: string; description: string; busy: boolean; submitLabel: string; onClose: () => void; onSubmit: (reason: string) => void }) { const [reason, setReason] = useState('业务范围变化，保留历史引用并停止进入新发布版本'); return <div className="tdw-backdrop"><section className="tdw-modal small"><header><div><Archive /><span><b>{title}</b><small>{description}</small></span></div><button onClick={onClose}><X /></button></header><label>原因<textarea value={reason} onChange={event => setReason(event.target.value)} /></label><footer><button onClick={onClose}>取消</button><button className="danger" disabled={busy || reason.trim().length < 2} onClick={() => onSubmit(reason.trim())}>{submitLabel}</button></footer></section></div> }

function executionMethod(content: TestCaseContent): TestExecutionMethod { return content.executionSpec?.method ?? content.executionMethods[0]?.method ?? 'ui' }
