import { Archive, Copy, FileClock, Filter, Layers3, Pencil, Plus, Save, Search, TestTube2, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import * as api from './api'
import { createEmptyTestCase, TestCaseEditor, testCaseEditorValid } from './TestCaseEditor'
import type { LibraryTestCase, LibraryTestSuiteVersion, TestCaseContent, TestCaseLibraryVersion, TestCaseTraceability, TestSuiteDraft } from './types'

type SuiteValue = api.SuiteDraftInput

export function TestCaseLibraryPanel({ projectId, cases, versions, suiteDrafts, suiteVersions, initialCaseId, busy, onCreate, onEdit, onCopy, onDeprecate, onSaveSuite }: { projectId: string; cases: LibraryTestCase[]; versions: TestCaseLibraryVersion[]; suiteDrafts: TestSuiteDraft[]; suiteVersions: LibraryTestSuiteVersion[]; initialCaseId?: string; busy: boolean; onCreate: (content: TestCaseContent, reason: string) => Promise<void>; onEdit: (testCase: LibraryTestCase, content: TestCaseContent, reason: string, traceability?: TestCaseTraceability) => Promise<void>; onCopy: (testCase: LibraryTestCase) => void; onDeprecate: (testCase: LibraryTestCase, reason: string) => void; onSaveSuite: (draft: TestSuiteDraft, value: SuiteValue) => void }) {
  const [query, setQuery] = useState(''); const [dimension, setDimension] = useState(''); const [method, setMethod] = useState(''); const [priority, setPriority] = useState(''); const [status, setStatus] = useState(initialCaseId ? '' : 'active')
  const [selectedId, setSelectedId] = useState<string | null>(initialCaseId ?? null); const [checked, setChecked] = useState<string[]>([]); const [editor, setEditor] = useState<LibraryTestCase | 'create' | null>(null); const [deprecating, setDeprecating] = useState<LibraryTestCase | null>(null)
  const restoredInitialCase = useRef(false)
  const filtered = useMemo(() => cases.filter(item => (!query || `${item.id} ${item.content.title}`.toLowerCase().includes(query.toLowerCase())) && (!dimension || item.content.dimension === dimension) && (!method || item.content.executionMethods.includes(method as 'ui' | 'api')) && (!priority || item.content.priority === priority) && (!status || item.status === status)), [cases, dimension, method, priority, query, status])
  const selected = filtered.find(item => item.id === selectedId) ?? filtered[0]
  const [detail, setDetail] = useState<LibraryTestCase | null>(null)
  useEffect(() => { setDetail(null); if (selected) void api.loadLibraryCase(projectId, selected.id).then(result => { setDetail(result.value); if (!restoredInitialCase.current && initialCaseId === result.value.id) { restoredInitialCase.current = true; setEditor(result.value) } }).catch(() => { setDetail(selected); if (!restoredInitialCase.current && initialCaseId === selected.id) { restoredInitialCase.current = true; setEditor(selected) } }) }, [initialCaseId, projectId, selected])
  return <section className="tdw-panel tdw-library"><header><div><span className="tdw-icon"><TestTube2 /></span><div><h2>项目级正式测试用例库</h2><p>Case ID 跨项目版本稳定；修改创建新 Revision，删除统一为废弃。</p></div></div><button className="primary" onClick={() => setEditor('create')}><Plus />新增正式用例</button></header>
    <div className="tdw-library-filters"><label className="search"><Search /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索 Case ID 或标题" /></label><Filter /><select value={dimension} onChange={event => setDimension(event.target.value)}><option value="">全部维度</option>{['functional', 'performance', 'stability', 'compatibility', 'security'].map(value => <option key={value}>{value}</option>)}</select><select value={method} onChange={event => setMethod(event.target.value)}><option value="">全部执行方式</option>{['ui', 'api'].map(value => <option key={value}>{value}</option>)}</select><select value={priority} onChange={event => setPriority(event.target.value)}><option value="">全部优先级</option>{['P0', 'P1', 'P2', 'P3'].map(value => <option key={value}>{value}</option>)}</select><select value={status} onChange={event => setStatus(event.target.value)}><option value="">全部状态</option><option value="active">active</option><option value="deprecated">deprecated</option></select></div>
    <div className="tdw-batchbar"><span>已选择 <b>{checked.length}</b> 条</span><select id="tdw-suite-target" defaultValue=""><option value="">选择套件草稿</option>{suiteDrafts.filter(item => item.status === 'draft' && item.compatibilityStatus !== 'migration_required').map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!checked.length || busy} onClick={() => { const element = document.querySelector<HTMLSelectElement>('#tdw-suite-target'); const draft = suiteDrafts.find(item => item.id === element?.value); const libraryVersion = versions.find(item => item.id === draft?.testCaseLibraryVersionId); if (!draft || !libraryVersion) return; const existing = new Set(draft.members.map(item => item.caseId)); const additions = checked.filter(id => !existing.has(id)).flatMap(id => { const member = libraryVersion.members.find(item => item.caseId === id); return member ? [suiteMemberInput(id, member.frozenContent, '从正式用例库批量加入')] : [] }); onSaveSuite(draft, { suiteKey: draft.suiteKey, suiteType: draft.suiteType, name: draft.name, testCaseLibraryVersionId: libraryVersion.id, members: [...draft.members.map(item => suiteMemberInput(item.caseId, undefined, item.reason, item.executionMethods)), ...additions] }); setChecked([]) }}><Layers3 />批量加入套件</button></div>
    {!filtered.length ? <div className="tdw-empty"><TestTube2 /><b>没有符合条件的正式用例</b><span>可调整筛选条件，或创建项目级正式用例。</span></div> : <div className="tdw-master-detail"><div className="tdw-master-list tdw-case-master">{filtered.map(item => <button key={item.id} className={selected?.id === item.id ? 'active' : ''} onClick={() => setSelectedId(item.id)}><input type="checkbox" checked={checked.includes(item.id)} onClick={event => event.stopPropagation()} onChange={() => setChecked(current => current.includes(item.id) ? current.filter(id => id !== item.id) : [...current, item.id])} /><span><b>{item.content.title}</b><small>{item.content.dimension} · {executionMethod(item.content)} · {item.content.priority}</small><code>{item.id} · r{item.currentRevision}</code></span><em className={item.status}>{item.status}</em></button>)}</div>{selected && <LibraryCaseDetail testCase={detail ?? selected} versions={versions} suites={suiteVersions} busy={busy} onEdit={() => setEditor(detail ?? selected)} onCopy={() => onCopy(detail ?? selected)} onDeprecate={() => setDeprecating(detail ?? selected)} />}</div>}
    {editor && <LibraryCaseEditor initial={editor === 'create' ? undefined : editor} busy={busy} onClose={() => setEditor(null)} onSave={async (content, reason, traceability) => { await (editor === 'create' ? onCreate(content, reason) : onEdit(editor, content, reason, traceability)); setEditor(null) }} />}
    {deprecating && <ReasonDialog title="废弃正式测试用例" description={`将 ${deprecating.id} 标记为 deprecated；所有历史 Revision 和发布引用继续保留。`} busy={busy} submitLabel="确认废弃" onClose={() => setDeprecating(null)} onSubmit={reason => { onDeprecate(deprecating, reason); setDeprecating(null) }} />}
  </section>
}

function LibraryCaseDetail({ testCase, versions, suites, busy, onEdit, onCopy, onDeprecate }: { testCase: LibraryTestCase; versions: TestCaseLibraryVersion[]; suites: LibraryTestSuiteVersion[]; busy: boolean; onEdit: () => void; onCopy: () => void; onDeprecate: () => void }) {
  const relatedSuites = suites.filter(suite => suite.members.some(item => item.caseId === testCase.id))
  const currentRevision = testCase.revisions?.find(item => item.revision === testCase.currentRevision)
  const relatedLibraryMembers = versions.flatMap(version => version.members.filter(member => member.caseId === testCase.id).map(member => ({ version, member })))
  return <article className="tdw-library-detail"><header><div><span className={`tdw-status ${testCase.status}`}>{testCase.status}</span><h3>{testCase.content.title}</h3><code>{testCase.id}</code></div><div><button disabled={busy || testCase.status === 'deprecated'} onClick={onEdit}><Pencil />编辑</button><button disabled={busy} onClick={onCopy}><Copy />复制</button><button disabled={busy || testCase.status === 'deprecated'} className="danger" onClick={onDeprecate}><Archive />废弃</button></div></header><div className="tdw-proposal-kpis"><span><small>当前 Revision</small><b>r{testCase.currentRevision}</b></span><span><small>维度</small><b>{testCase.content.dimension}</b></span><span><small>执行方式</small><b>{executionMethod(testCase.content)}</b></span><span><small>优先级</small><b>{testCase.content.priority}</b></span></div><section><h4>Revision 原始追溯</h4>{currentRevision?.traceability ? <Traceability traceability={currentRevision.traceability} /> : <p className="tdw-muted">未建立 Revision 原始追溯</p>}</section><section><h4>前置条件</h4>{testCase.content.preconditions.length ? <ol>{testCase.content.preconditions.map((item, index) => <li key={index}>{item}</li>)}</ol> : <p className="tdw-muted">无</p>}</section><section><h4>测试步骤</h4><ol>{testCase.content.steps.map((item, index) => <li key={index}>{item}</li>)}</ol></section><section><h4>预期结果</h4><ol>{testCase.content.expectedResults.map((item, index) => <li key={index}>{item}</li>)}</ol></section><section><h4>Library Version Member 当前版本追溯</h4>{relatedLibraryMembers.length ? <div className="tdw-traceability-list">{relatedLibraryMembers.map(({ version, member }) => <article key={`${version.id}:${member.caseId}:${member.revision}`}><b>Library Version V{version.version} · {version.name}</b><small>{version.id} · member r{member.revision}</small>{member.traceability ? <Traceability traceability={member.traceability} emptyLabel="扩展测试 / 当前版本无 Requirement direct trace" /> : <p className="tdw-muted">未建立 Library Version Member 当前版本追溯</p>}</article>)}</div> : <p className="tdw-muted">尚未关联正式 Library Version。</p>}</section><section><h4>关联测试套件</h4>{relatedSuites.length ? <div className="tdw-chips">{relatedSuites.map(item => <span key={item.id}>{item.name} V{item.version}</span>)}</div> : <p className="tdw-muted">尚未加入已发布套件。</p>}</section><section><h4>Revision 历史</h4><div className="tdw-revisions">{[...(testCase.revisions ?? [])].reverse().map(item => <article key={item.revision}><FileClock /><span><b>Revision {item.revision}</b><small>{item.changeReason} · {item.createdBy} · {new Date(item.createdAt).toLocaleString('zh-CN')}</small><code>{item.contentSha256}</code></span></article>)}</div></section></article>
}

function Traceability({ traceability, emptyLabel = '该 Revision 创建时无 Requirement direct trace' }: { traceability: TestCaseTraceability; emptyLabel?: string }) {
  return <div className="tdw-traceability"><span><small>Requirement Release</small><code>{traceability.sourceRequirementReleaseId}</code></span><span><small>Requirement</small>{traceability.requirementRefs.length ? <div className="tdw-chips">{traceability.requirementRefs.map(item => <code key={`${item.requirementReleaseId}:${item.requirementId}`}>{item.requirementId}</code>)}</div> : <p className="tdw-muted">{emptyLabel}</p>}</span></div>
}

function LibraryCaseEditor({ initial, busy, onClose, onSave }: { initial?: LibraryTestCase; busy: boolean; onClose: () => void; onSave: (content: TestCaseContent, reason: string, traceability?: TestCaseTraceability) => Promise<void> }) {
  const [content, setContent] = useState<TestCaseContent>(() => initial?.content ? structuredClone(initial.content) : createEmptyTestCase())
  const [reason, setReason] = useState(initial ? '人工维护正式用例' : '人工新增正式用例')
  const [traceabilityText, setTraceabilityText] = useState('')
  let traceability: TestCaseTraceability | undefined
  let traceabilityError = ''
  if (traceabilityText.trim()) {
    try { traceability = JSON.parse(traceabilityText) as TestCaseTraceability } catch { traceabilityError = '追溯 JSON 格式无效' }
  }
  const currentTraceability = initial?.revisions?.find(item => item.revision === initial.currentRevision)?.traceability
  return <div className="tdw-backdrop"><section className="tdw-modal wide"><header><div><Pencil /><span><b>{initial ? `编辑 ${initial.id} · 新建 Revision` : '新增正式测试用例'}</b><small>编辑统一 TestCase v3 语义字段；服务端负责 ID、Hash、Revision 与历史追溯。</small></span></div><button onClick={onClose}><X /></button></header><TestCaseEditor value={content} onChange={setContent} /><label>变更原因<input value={reason} onChange={event => setReason(event.target.value)} /></label>{initial && <label>新 Revision 追溯（可选 JSON）<textarea value={traceabilityText} onChange={event => setTraceabilityText(event.target.value)} placeholder="通常可留空继承；需要重新绑定 Requirement Release 时提交固定追溯。" /><small>{traceabilityError || (currentTraceability ? `当前追溯：${JSON.stringify(currentTraceability)}` : '历史数据未建立正式追溯')}</small></label>}<footer><button onClick={onClose}>取消</button><button className="primary" disabled={busy || !reason.trim() || Boolean(traceabilityError) || !testCaseEditorValid(content)} onClick={() => void onSave(content, reason.trim(), traceability).catch(() => undefined)}><Save />保存</button></footer></section></div>
}

function ReasonDialog({ title, description, busy, submitLabel, onClose, onSubmit }: { title: string; description: string; busy: boolean; submitLabel: string; onClose: () => void; onSubmit: (reason: string) => void }) { const [reason, setReason] = useState('业务范围变化，保留历史引用并停止进入新发布版本'); return <div className="tdw-backdrop"><section className="tdw-modal small"><header><div><Archive /><span><b>{title}</b><small>{description}</small></span></div><button onClick={onClose}><X /></button></header><label>原因<textarea value={reason} onChange={event => setReason(event.target.value)} /></label><footer><button onClick={onClose}>取消</button><button className="danger" disabled={busy || reason.trim().length < 2} onClick={() => onSubmit(reason.trim())}>{submitLabel}</button></footer></section></div> }

function executionMethod(content: TestCaseContent): string { return content.executionMethods.map(item => item.toUpperCase()).join(' + ') }
function suiteMemberInput(caseId: string, content: TestCaseContent | undefined, reason: string, existingMethods?: Array<'ui' | 'api'>): SuiteValue['members'][number] {
  const methods = existingMethods?.length ? existingMethods : content ? content.executionMethods : []
  return { caseId, executionMethods: (['ui', 'api'] as const).filter((method): method is 'ui' | 'api' => methods.includes(method)), reason }
}
