import { Activity, Bot, Boxes, ClipboardList, Database, FileDiff, FolderOpen, Library, LockKeyhole, PackageCheck, RefreshCw, Rocket, Settings2, TestTube2, Workflow } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import type { ProjectVersion } from '../project-version-api'
import { CaseChangeProposalPanel } from './CaseChangeProposalPanel'
import { CoverageAuditPanel } from './CoverageAuditPanel'
import { TestCaseLibraryPanel } from './TestCaseLibraryPanel'
import { TestCasePanel } from './TestCasePanel'
import { TestDesignCreatePanel } from './TestDesignCreatePanel'
import { TestDataRequirementPanel } from './TestDataRequirementPanel'
import { TestDesignPublicationPanel } from './TestDesignPublicationPanel'
import { TestDesignRunPanel } from './TestDesignRunPanel'
import { TestSuiteLibraryPanel } from './TestSuiteLibraryPanel'
import { useTestDesign } from './hooks/useTestDesign'
import type { AgentEvent, TestDesignWorkflowRun } from './types'
import './test-design.css'

type Notify = (message: string, tone?: 'success' | 'error' | 'warning') => void
type Entry = 'designs' | 'library' | 'suites' | 'releases'
type DesignTab = 'cases' | 'data' | 'proposals' | 'audit' | 'publish' | 'details'

const entries: Array<{ key: Entry; label: string; icon: typeof ClipboardList }> = [{ key: 'designs', label: '设计任务', icon: ClipboardList }, { key: 'library', label: '测试用例库', icon: Library }, { key: 'suites', label: '测试套件', icon: Workflow }, { key: 'releases', label: '发布记录', icon: Rocket }]
const designTabs: Array<{ key: DesignTab; label: string; icon: typeof ClipboardList }> = [{ key: 'cases', label: '测试用例', icon: TestTube2 }, { key: 'data', label: '测试数据需求', icon: Database }, { key: 'audit', label: 'Coverage 状态', icon: Activity }, { key: 'proposals', label: '用例库变更', icon: FileDiff }, { key: 'publish', label: '审核并发布', icon: Rocket }, { key: 'details', label: '详细信息', icon: Settings2 }]

export function TestDesignPage({ projectVersion, onManageVersions, notify, embedded = false, linkedDesignId, linkedRunId, initialCreate = false }: { projectVersion: ProjectVersion | null; onManageVersions: () => void; notify: Notify; embedded?: boolean; linkedDesignId?: string; linkedRunId?: string; initialCreate?: boolean }) {
  const routedEntry = new URL(window.location.href).searchParams.get('testDesignEntry')
  const model = useTestDesign(projectVersion?.id, notify); const [entry, setEntry] = useState<Entry>(routedEntry === 'library' ? 'library' : 'designs'); const [tab, setTab] = useState<DesignTab>('cases'); const [creating, setCreating] = useState(initialCreate); const autoOpeningId = useRef(''); const linkedOpeningId = useRef('')
  const linkedTargetId = linkedDesignId && linkedRunId ? `${linkedDesignId}:${linkedRunId}` : ''
  useEffect(() => {
    if (!linkedDesignId || !linkedRunId || (model.design?.id === linkedDesignId && model.run?.id === linkedRunId) || linkedOpeningId.current === linkedTargetId) return
    linkedOpeningId.current = linkedTargetId
    void model.openLinkedRun(linkedDesignId, linkedRunId)
      .catch(() => undefined)
      .finally(() => { linkedOpeningId.current = '' })
  }, [linkedDesignId, linkedRunId, linkedTargetId, model.design?.id, model.run?.id, model.openLinkedRun])
  useEffect(() => { const candidate = model.designs[0]; if (embedded || linkedTargetId || !candidate || model.design || creating || autoOpeningId.current === candidate.id) return; autoOpeningId.current = candidate.id; void model.openDesign(candidate).finally(() => { autoOpeningId.current = '' }) }, [creating, embedded, linkedTargetId, model.design, model.designs[0]?.id])
  useEffect(() => { if (model.run?.stage === 'test_case_design' || model.run?.stage === 'completed') setTab('cases') }, [model.run?.stage])
  if (!projectVersion) return <main className="td2-shell"><section className="td2-card td2-empty"><Boxes /><h2>请先选择 ProjectVersion</h2><p>测试设计的 Requirement Release、Workspace 与正式产物都按项目版本隔离。</p><button className="td2-button primary" onClick={onManageVersions}>管理项目版本</button></section></main>
  if (embedded && (!model.inputs || (linkedTargetId && (!model.design || !model.run)))) return <EmbeddedTestDesignLoading contextReady={Boolean(model.inputs)} error={model.error} onRetry={linkedDesignId && linkedRunId ? () => { void model.openLinkedRun(linkedDesignId, linkedRunId).catch(() => undefined) } : undefined} />
  if (!model.inputs) return <main className="td2-shell"><section className="td2-card td2-empty"><RefreshCw className="spin" /><h2>正在读取测试设计上下文</h2><p>检查 Requirement Release 绑定、正式用例库、测试套件与 PlanningAgent 配置。</p>{model.error && <div className="td2-error">{model.error}</div>}</section></main>
  const projectId = model.inputs.projectVersion.projectId
  if (embedded) return <section className="tdw-embedded" aria-label="测试用例">
    {model.error && <div className="tdw-global-error"><b>操作未完成</b><span>{model.error}</span></div>}
    {entry === 'designs' && <DesignWorkspace creating={creating} tab={tab} setTab={setTab} model={model} onCreateDone={() => setCreating(false)} />}
    {entry === 'library' && <div className="tdw-content"><LegacyMigrationBanner model={model} /><TestCaseLibraryPanel projectId={projectId} cases={model.libraryCases} versions={model.libraryVersions} suiteDrafts={model.suiteDrafts} suiteVersions={model.suiteVersions} initialCaseId={new URL(window.location.href).searchParams.get('libraryCaseId') ?? undefined} busy={Boolean(model.busy)} onCreate={(content, reason) => model.createLibraryCase(content, reason)} onEdit={(testCase, content, reason, traceability) => model.editLibraryCase(testCase, content, reason, traceability)} onCopy={testCase => void model.copyLibraryCase(testCase)} onDeprecate={(testCase, reason) => void model.deprecateLibraryCase(testCase, reason)} onSaveSuite={(draft, value) => void model.saveSuiteDraft(draft, value)} /></div>}
    {entry === 'suites' && <div className="tdw-content"><TestSuiteLibraryPanel projectId={projectId} cases={model.libraryCases} libraryVersions={model.libraryVersions} drafts={model.suiteDrafts} versions={model.suiteVersions} busy={Boolean(model.busy)} onSave={(draft, value) => void model.saveSuiteDraft(draft, value)} onPublish={draft => void model.publishSuite(draft)} onDeprecate={version => void model.deprecateSuite(version)} /></div>}
    {entry === 'releases' && <div className="tdw-content"><TestDesignPublicationPanel projectId={projectId} cases={model.libraryCases} versions={model.libraryVersions} suites={model.suiteVersions} handoffs={model.handoffs} busy={Boolean(model.busy)} onHandoff={(version, mode, suiteId, impacted, overrides) => void model.handoff(version, mode, suiteId, impacted, overrides)} /></div>}
  </section>
  return <main className="tdw-page"><header className="tdw-header"><div className="tdw-title"><span><TestTube2 /></span><div><h1>测试设计</h1><p>{projectVersion.name} · 同一 PlanningAgent / Planning Session</p></div></div><nav>{entries.map(item => <button key={item.key} className={entry === item.key ? 'active' : ''} onClick={() => { setEntry(item.key); setCreating(false) }}><item.icon />{item.label}</button>)}</nav><div className="tdw-header-context"><span className={model.inputs.requirementRelease ? 'bound' : 'missing'}><LockKeyhole /><small>Requirement Release</small><b>{model.inputs.requirementRelease?.id.slice(-10) ?? '未绑定'}</b></span><button onClick={onManageVersions}><Settings2 />项目版本</button></div></header>
    {model.error && <div className="tdw-global-error"><b>操作未完成</b><span>{model.error}</span></div>}
    <div className="tdw-layout"><WorkspaceSidebar entry={entry} model={model} selectedId={model.design?.id} onCreate={() => { setEntry('designs'); setCreating(true) }} onOpen={design => { setCreating(false); setTab('cases'); void model.openDesign(design) }} />
      <section className="tdw-main">{entry === 'designs' && <DesignWorkspace creating={creating} tab={tab} setTab={setTab} model={model} onCreateDone={() => setCreating(false)} />}{entry === 'library' && <div className="tdw-content"><LegacyMigrationBanner model={model} /><TestCaseLibraryPanel projectId={projectId} cases={model.libraryCases} versions={model.libraryVersions} suiteDrafts={model.suiteDrafts} suiteVersions={model.suiteVersions} initialCaseId={new URL(window.location.href).searchParams.get('libraryCaseId') ?? undefined} busy={Boolean(model.busy)} onCreate={(content, reason) => model.createLibraryCase(content, reason)} onEdit={(testCase, content, reason, traceability) => model.editLibraryCase(testCase, content, reason, traceability)} onCopy={testCase => void model.copyLibraryCase(testCase)} onDeprecate={(testCase, reason) => void model.deprecateLibraryCase(testCase, reason)} onSaveSuite={(draft, value) => void model.saveSuiteDraft(draft, value)} /></div>}{entry === 'suites' && <div className="tdw-content"><TestSuiteLibraryPanel projectId={projectId} cases={model.libraryCases} libraryVersions={model.libraryVersions} drafts={model.suiteDrafts} versions={model.suiteVersions} busy={Boolean(model.busy)} onSave={(draft, value) => void model.saveSuiteDraft(draft, value)} onPublish={draft => void model.publishSuite(draft)} onDeprecate={version => void model.deprecateSuite(version)} /></div>}{entry === 'releases' && <div className="tdw-content"><TestDesignPublicationPanel projectId={projectId} cases={model.libraryCases} versions={model.libraryVersions} suites={model.suiteVersions} handoffs={model.handoffs} busy={Boolean(model.busy)} onHandoff={(version, mode, suiteId, impacted, overrides) => void model.handoff(version, mode, suiteId, impacted, overrides)} /></div>}</section>
      <ContextSidebar entry={entry} model={model} />
    </div>
  </main>
}

function DesignWorkspace({ creating, tab, setTab, model, onCreateDone }: { creating: boolean; tab: DesignTab; setTab: (tab: DesignTab) => void; model: ReturnType<typeof useTestDesign>; onCreateDone: () => void }) {
  const [handoffFocusRequest, setHandoffFocusRequest] = useState(0)
  const openHandoff = () => { setTab('publish'); setHandoffFocusRequest(current => current + 1) }
  if (creating) return <div className="tdw-content"><TestDesignCreatePanel inputs={model.inputs!} busy={Boolean(model.busy)} onCancel={onCreateDone} onCreate={async input => { await model.create(input); onCreateDone() }} /></div>
  if (!model.design) return <div className="tdw-content"><section className="tdw-welcome"><div><Bot /><span><p>PlanningAgent</p><h2>等待 Requirement Release</h2><p>正式需求版本发布后，Service 会自动创建测试设计并直接生成多场景测试用例与 Coverage Audit。</p></span></div><div className="tdw-pipeline">{['需求基线', '必要时人工澄清', 'AI 测试用例生成', 'Coverage Audit', '最终人工审核', '发布 / Handoff'].map((item, index) => <span key={item}><i>{index + 1}</i>{item}</span>)}</div></section></div>
  const run = model.run
  const auditBadge = auditTabBadge(run)
  return <>
    <nav className="tdw-tabs">{designTabs.map(item => <button key={item.key} className={tab === item.key ? 'tdw-tab-active' : ''} onClick={() => setTab(item.key)}><item.icon />{item.label}{item.key === 'data' && <i>{run?.dataSetVersions.at(-1)?.requirements.length ?? 0}</i>}{item.key === 'proposals' && <i>{run?.caseChangeProposals.filter(proposal => proposal.decision === 'pending').length ?? 0}</i>}{item.key === 'audit' && <i title="Coverage 发布状态">{auditBadge}</i>}</button>)}</nav>
    <div className="tdw-content">
      {tab === 'cases' && run ? <TestCasePanel run={run} busy={Boolean(model.busy)} onBatchApprove={() => void model.reviewCases()} onResynthesize={() => void model.resynthesize()} onCreate={content => void model.createCase(content)} onEdit={(caseId, content, reason) => void model.editCase(caseId, content, reason)} onDelete={caseId => void model.removeCase(caseId)} onReview={(caseId, decision, revision, comment) => void model.reviewCase(caseId, decision, revision, comment)} /> : tab === 'cases' ? <EmptyTab icon={<TestTube2 />} title="Agent 正在设计测试" text="PlanningAgent 正在直接从 Requirement Release 展开测试场景。" /> : null}
      {tab === 'data' && run ? <TestDataRequirementPanel run={run} /> : tab === 'data' ? <EmptyTab icon={<Database />} title="尚无测试数据需求" text="PlanningAgent 完成用例设计后会独立保存数据需求定义。" /> : null}
      {tab === 'proposals' && run ? <CaseChangeProposalPanel run={run} busy={Boolean(model.busy)} onDecision={(id, decision, comment, content) => void model.decideProposal(id, decision, comment, content)} /> : tab === 'proposals' ? <EmptyTab icon={<FileDiff />} title="尚无用例库变更" text="候选用例生成时，Agent 会同步提交新增、修改、复用与废弃 Proposal。" /> : null}
      {tab === 'audit' && run ? <CoverageAuditPanel run={run} busy={Boolean(model.busy)} onAudit={() => void model.reAudit()} onResolve={(kind, id, version) => void model.resolveIssue(kind, id, version)} onOpenHandoff={openHandoff} /> : tab === 'audit' ? <EmptyTab icon={<Activity />} title="尚无 Coverage Audit" text="用例生成后由服务端自动执行确定性覆盖审计。" /> : null}
      {tab === 'publish' && run ? <TestDesignPublicationPanel projectId={model.inputs!.projectVersion.projectId} run={run} cases={model.libraryCases} versions={model.libraryVersions} suites={model.suiteVersions} handoffs={model.handoffs} busy={Boolean(model.busy)} handoffFocusRequest={handoffFocusRequest} onPublish={name => void model.publish(name)} onHandoff={(version, mode, suiteId, impacted, overrides) => void model.handoff(version, mode, suiteId, impacted, overrides)} /> : tab === 'publish' ? <EmptyTab icon={<Rocket />} title="尚未运行" text="完成人工用例审核、Coverage Audit 与 Proposal 处置后发布正式用例库版本。" /> : null}
      {tab === 'details' && <div className="tdw-advanced-details"><TestDesignRunPanel design={model.design} run={run} busy={Boolean(model.busy)} onStartRun={() => void model.startRun()} onRefresh={() => void model.refreshRun()} /></div>}
    </div>
  </>
}

function auditTabBadge(run?: TestDesignWorkflowRun | null) {
  const audit = run?.coverageAudits.at(-1)
  if (!audit) return '—'
  if (audit.status === 'stale') return '待查'
  const publicationBlockerCount = audit.blockers.filter(item => item.resolution !== 'execution_handoff').length
  return publicationBlockerCount ? String(publicationBlockerCount) : '通过'
}

function WorkspaceSidebar({ entry, model, selectedId, onCreate, onOpen }: { entry: Entry; model: ReturnType<typeof useTestDesign>; selectedId?: string; onCreate: () => void; onOpen: (design: ReturnType<typeof useTestDesign>['designs'][number]) => void }) {
  const title = ({ designs: '设计任务', library: '正式用例', suites: '套件资产', releases: '发布版本' } as const)[entry]
  return <aside className="tdw-workspace"><header><span><FolderOpen />{title}</span>{entry === 'designs' && <button onClick={onCreate} title="高级设置：手动创建测试设计" aria-label="高级设置：手动创建测试设计"><Settings2 /></button>}</header><div className="tdw-path">project/{model.inputs?.projectVersion.projectId}/{entry}</div><div className="tdw-docs">{entry === 'designs' && model.designs.map(item => <button key={item.id} className={selectedId === item.id ? 'active' : ''} onClick={() => onOpen(item)}><span><ClipboardList /></span><div><b>{item.name}</b><small>{item.latestRun ? `${stageLabel(item.latestRun.stage)} · ${item.latestRun.progress}%` : '尚未运行'}</small><em>{item.creationMode === 'automatic' ? 'PlanningAgent 自动创建 · ' : '高级设置创建 · '}{item.id}</em></div></button>)}{entry === 'library' && model.libraryCases.map(item => <button key={item.id}><span><TestTube2 /></span><div><b>{item.content.title}</b><small>{item.content.dimension} · r{item.currentRevision} · {item.status}</small><em>{item.id}</em></div></button>)}{entry === 'suites' && [...model.suiteDrafts, ...model.suiteVersions].map(item => <button key={item.id}><span><Workflow /></span><div><b>{item.name}</b><small>{item.suiteType} · {item.members.length} 条</small><em>{item.id}</em></div></button>)}{entry === 'releases' && model.libraryVersions.map(item => <button key={item.id}><span><PackageCheck /></span><div><b>V{item.version} · {item.name}</b><small>{item.members.length} 条 · {item.projection.status}</small><em>{item.id}</em></div></button>)}</div><footer><button onClick={() => void model.loadCollection()}><RefreshCw />刷新项目资产</button></footer></aside>
}

function ContextSidebar({ entry, model }: { entry: Entry; model: ReturnType<typeof useTestDesign> }) { const events = useMemo(() => model.run?.nodeRuns.flatMap(node => node.execution?.events ?? []).sort((left, right) => right.sequence - left.sequence) ?? [], [model.run]); return <aside className="tdw-agent"><header><span><Bot />{entry === 'designs' ? 'Agent 运行轨迹' : '资产上下文'}</span><span className="tdw-live">● LIVE</span></header><div className="tdw-trace">{entry === 'designs' && model.run ? <><div className="tdw-agent-summary"><Bot /><span><b>PlanningAgent</b><small>{model.run.agentConfigurationSnapshot.primaryModel.modelName} · {model.run.status} · {model.run.progress}%</small></span></div>{events.slice(0, 30).map(event => <article key={`${event.sequence}-${event.type}`} className={event.toolId ? 'tool' : ''}><small>#{event.sequence} · {event.type}</small><b>{skillReadLabel(event) ?? event.toolId ?? event.content?.slice(0, 80) ?? '工作流事件'}</b><time>{event.occurredAt ? new Date(event.occurredAt).toLocaleTimeString('zh-CN') : ''}</time></article>)}</> : <AssetSummary model={model} />}</div></aside> }
function EmbeddedTestDesignLoading({ contextReady, error, onRetry }: { contextReady: boolean; error: string; onRetry?: () => void }) { const title = contextReady ? '正在打开本次测试用例' : '正在建立测试设计上下文'; const detail = contextReady ? '上下文已确认，正在读取冻结运行、候选用例及其 Coverage 状态。' : '正在确认 Requirement Release，并读取本次测试设计入口。'; return <section className="tdw-embedded tdw-context-loading" aria-label="测试用例加载中" aria-busy="true"><div className="tdw-context-loading-card"><div className="tdw-context-loading-head"><span><RefreshCw className="spin" /></span><div><b>{title}</b><small>{detail}</small></div></div><div className="tdw-context-loading-skeleton" aria-hidden="true"><i /><i /><i /></div>{error && <div className="tdw-context-loading-error"><span>{error}</span>{onRetry && <button onClick={onRetry}>重试读取</button>}</div>}</div></section> }
function skillReadLabel(event: AgentEvent) { if (!event.skillKey) return undefined; return `${event.type === 'skill_read_replayed' ? 'Skill 缓存重放' : 'Skill 已读取'}：${event.skillKey}${event.version ? ` · v${event.version}` : ''}` }
function AssetSummary({ model }: { model: ReturnType<typeof useTestDesign> }) { return <><div className="tdw-agent-summary"><Library /><span><b>项目级测试资产</b><small>当前快照实时来自服务端</small></span></div><div className="tdw-context-kpis"><span><b>{model.libraryCases.length}</b><small>正式用例</small></span><span><b>{model.libraryVersions.length}</b><small>用例库版本</small></span><span><b>{model.suiteDrafts.length}</b><small>套件草稿</small></span><span><b>{model.suiteVersions.length}</b><small>套件版本</small></span><span><b>{model.handoffs.length}</b><small>Handoff</small></span></div></> }
function LegacyMigrationBanner({ model }: { model: ReturnType<typeof useTestDesign> }) { const legacy = model.inputs?.historicalCaseSets[0]; if (!legacy || model.libraryVersions.length) return null; const preview = model.legacyMigrationPreview; return <section className="tdw-legacy-migration"><div><PackageCheck /><span><b>检测到历史已发布用例集</b><small>{legacy.name} · V{legacy.version} · {legacy.memberCount} 条；不会在启动时自动改变历史数据。</small></span></div><div><button disabled={Boolean(model.busy)} onClick={() => void model.previewLegacyMigration(legacy.id)}>查看迁移预览</button><button className="primary" disabled={Boolean(model.busy)} onClick={() => void model.migrateLegacyCaseSet(legacy.id, preview?.status === 'needs_confirmation')}>{preview?.status === 'needs_confirmation' ? '人工确认并导入' : '导入正式用例库'}</button></div>{preview && <section><header><b>迁移预览 · {preview.status}</b><code>{preview.previewSha256}</code></header>{preview.items.map(item => <article key={`${item.legacyCaseId}:${item.legacyRevision}`}><code>{item.legacyCaseId} r{item.legacyRevision}</code><span>→ {item.suggestedLibraryCaseId}</span><em>{item.resolution} · {item.executionConfigurationStatus}</em>{item.executionConfigurationIssues.length > 0 && <small>{item.executionConfigurationIssues.join('；')}</small>}</article>)}</section>}</section> }
function EmptyTab({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <div className="tdw-empty">{icon}<b>{title}</b><span>{text}</span></div> }
function stageLabel(value: string) { return ({ test_case_design: '用例生成', coverage_audit: 'Coverage 检查', test_design_repair: '自动修复', completed: '已完成' } as Record<string, string>)[value] ?? value }
